#!/bin/bash
# Auto-generated script to build RAG data for Elixir dependencies

uv run python rag_builder.py build bcrypt_elixir 3.3.2
uv run python rag_builder.py build phoenix 1.7.21
uv run python rag_builder.py build phoenix_ecto 4.6.5
uv run python rag_builder.py build ecto_sql 3.13.2
uv run python rag_builder.py build postgrex 0.20.0
uv run python rag_builder.py build phoenix_html 4.2.1
uv run python rag_builder.py build phoenix_live_reload 1.6.0
uv run python rag_builder.py build phoenix_live_view 1.0.17
uv run python rag_builder.py build floki 0.38.0
uv run python rag_builder.py build phoenix_live_dashboard 0.8.7
uv run python rag_builder.py build esbuild 0.10.0
uv run python rag_builder.py build tailwind 0.3.1
uv run python rag_builder.py build telemetry_metrics 1.1.0
uv run python rag_builder.py build telemetry_poller 1.3.0
uv run python rag_builder.py build gettext 0.26.2
uv run python rag_builder.py build jason 1.4.4
uv run python rag_builder.py build dns_cluster 0.2.0
uv run python rag_builder.py build bandit 1.7.0
uv run python rag_builder.py build swoosh 1.19.5
uv run python rag_builder.py build hackney 1.25.0
uv run python rag_builder.py build uuid 1.1.8
uv run python rag_builder.py build cachex 4.1.1
uv run python rag_builder.py build deep_merge 1.0.0
uv run python rag_builder.py build timex 3.7.13
uv run python rag_builder.py build nimble_csv 1.3.0
uv run python rag_builder.py build ymlr 5.1.4
uv run python rag_builder.py build yaml_elixir 2.11.0
uv run python rag_builder.py build algoliax 0.10.0
uv run python rag_builder.py build ex_aws 2.5.10
uv run python rag_builder.py build ex_aws_s3 2.5.7
uv run python rag_builder.py build sweet_xml 0.7.5
uv run python rag_builder.py build mogrify 0.9.3
uv run python rag_builder.py build oban 2.19.4
uv run python rag_builder.py build igniter 0.6.25
uv run python rag_builder.py build oban_web 2.11.3
uv run python rag_builder.py build polymorphic_embed 5.0.3
uv run python rag_builder.py build calendar_translations 0.0.4
uv run python rag_builder.py build goth 1.4.5
uv run python rag_builder.py build tesla 1.15.2
uv run python rag_builder.py build solid 1.0.1
uv run python rag_builder.py build earmark 1.4.48
uv run python rag_builder.py build joken 2.6.2
uv run python rag_builder.py build live_debugger 0.3.1
uv run python rag_builder.py build tidewave 0.2.0
uv run python rag_builder.py build dialyxir 1.4.5
uv run python rag_builder.py build sobelow 0.14.0
uv run python rag_builder.py build ex_doc 0.38.2
uv run python rag_builder.py build credo 1.7.12
uv run python rag_builder.py build excoveralls 0.18.5
uv run python rag_builder.py build mix_test_watch 1.3.0
uv run python rag_builder.py build faker 0.18.0
uv run python rag_builder.py build ex_machina 2.8.0
uv run python rag_builder.py build mock 0.3.9
uv run python rag_builder.py build mox 1.2.0
uv run python rag_builder.py build bypass 2.1.0
uv run python rag_builder.py build sentry 11.0.2
