services:
  chromadb:
    image: chromadb/chroma
    ports:
      - "8003:8000"
    volumes:
      - ./chroma_data:/chroma
    environment:
      - IS_PERSISTENT=TRUE

  pgvector-db:
    image: ankane/pgvector
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
